### ISSUE TITLE
Unable to use in a multiplayer custom scenario

### ISSUE THREAD

**Issue by maartendeblock** [Afforess/Factorio-Stdlib#67] opened 2017-03-17 11:22 UTC
When the files are present in multiplayer custom scenario (even when there is no require in control.lua), players can't join.

They can connect and then they get dropped with the message:
factorio cannot load downloaded map create_directory(p) operation not permitted

**Comment by Afforess** [comment] 2017-03-18 01:54
I'm not super familiar with custom scenarios... Any chance you can upload a copy you have showing this bug? Or instructions on how to set one up myself?

**Comment by Nexela** [comment] 2017-05-07 02:23
My guess is a permissions issue with the files in the scenario? Or more likely subfolders are not allowed inside scenarios.

**Comment by Nexela** [comment] 2017-05-24 18:47
I would close this one for now.   Pretty sure it was related to a fixed factorio bug regarding folders in scenarios.    Additionally Custom modded scenarios are a nightmare :)

**Comment by Afforess** [comment] 2017-05-24 19:34
@Nexela any idea which factorio version this was fixed in?

**Comment by Nexela** [comment] 2017-05-24 21:22
Hmm thought I seen something about it in a change log.  but devs have moved to I/O
https://forums.factorio.com/viewtopic.php?t=46206&p=265411

**Comment by Afforess** [comment] 2017-05-24 21:31
If they can't reproduce it, I don't think it's a problem with stdlib.

**Closed by Afforess** 2017-05-24 21:31 UTC
Labels: bug, help wanted
